### ISSUE TITLE
Component_ZendHttp/zipball not found

### ISSUE THREAD

**Issue by sam0hack** [zendframework/subsplit#1]
https://api.github.com/repos/zendframework/Component_ZendHttp/zipball/release-2.1.4 is not found maybe url changed

**Comment by weierophinney** [comment]
It did, almost a year ago; please check under zendframework/zend-http.

**Comment by sam0hack** [comment]
Yes here is the new URL    https://api.github.com/repos/zendframework/zend-stdlib/zipball/426b5396e89e7da2db9678bc9a0b57865f84fe0f
